### ISSUE TITLE
Crash if no --dump-flowmap is not used.  

### ISSUE THREAD

**Issue by dwbullok** [smcameron/gaseous-giganticus#5]
If --dump-flowmap is not used, the program crashes.  The program runs fine if I use the --dump-flowmap option.  I believe the error is at gaseous-giganticus.c: 1915.  If I'm reading it correctly, the program tries to save a flowmap even when there is no flowmap image to save.

**Comment by smcameron** [comment]
Thanks for reporting this.  Should have a fix in a few minutes.

**Comment by smcameron** [comment]
Alright should be fixed now.
